#############
# MultiChat #
#############

# For a startup guide please see [SOON]

# Settings for changing the chat up into a global and local channel
LocalAndGlobalChat: true
GlobalChatPrefix: '%'
LocalRadius: 50
# For these prefixes you can use the placeholders:
#  %player% : playername
#  %message% : message
#  %prefix% : Luckperms prefix
Local_Prefix: "&7[Local] %prefix% &f%player% >> %message%"
Global_Prefix: "&7[Global] %prefix% &f%player% >> %message%"

# Translator settings
EnableTranslations: true
AllowFreeLanguageChoice: true
ForceLanguage: false
ForcedLanguage: 'ENG'
DefaultLanguage: 'ENG'
# This prefix is only relevant if LocalAndGlobalChat is False
# You can use the placeholders:
#  %player% : playername
#  %message% : message
#  %prefix% : Luckperms prefix
Translator_Prefix: "%prefix% %player% >> %message%"